### PR TITLE
Add function to throw out old visual before re-rendering int node vis

### LINKED ISSUE #311: IntNode: Fix update
Currently on update the int node matrix does not redraw nicely

### PR DESCRIPTION
**Pull request by JackWilb**
Closes #311

Removing the visual elements and redrawing is the fastest path to what we want. We should check that we're not missing any data because of a weird enter/exit issue.

Let me know what you think @gotdairyya. We could also try to approach this in a smarter way, using ids and the proper d3 enter exit merge, but it might be more work than it's worth

### CODE REVIEW

**Comment by gotdairyya** [comment]
Not sure why your code doesn't work. There are 2 main issues

(1) it does not update the gridlines:

_This is switching from 2 hops to 3 hops_
image

(2) The color scale doesn't reset
_This is switching from 3 hops to 2 hop_
image

**Review by gotdairyya — CHANGES_REQUESTED** [review]
It looks like it should work, but the elements aren't being rebuilt correctly when switching across different hop size queries

**Comment by gotdairyya** [comment]
those edits fixed most of the issues! 

two things coming up though:
(1) I'm still not seeing the correct color scale though when I go from 3 hop to 2 hop

(2) in going from a 2 hop query to a 1 hop query (so the int node table disappears) and then back to a 2 hop this happens:
image

**Review by gotdairyya — CHANGES_REQUESTED** [review]
The gridlines are redrawn correctly, but the color scales don't update

**Comment by JackWilb** [comment]
Looks good with 3503454 and fc27a71

**Review by gotdairyya — APPROVED** [review]

**Pull request merged**
