### PR TITLE
Make query pretty

### PR DESCRIPTION
**Pull request by gotdairyya**
Focused on readability and some UX
Super open to suggestions!

### CODE REVIEW

**Comment by JackWilb** [comment]
My feedback so far is that it'd be nice if the nodes/edges were numbered (e.g. start node, int node 1, end node, etc.).

We could also probably use some icons, but I'm not sure which and where to place them for them to be most effective.

**Review by jtomeck — APPROVED** [review]
I committed some changes just now. Let me know what you think.

MDI comes with icons inside circles up to 10. I think that should be enough, but do you forsee the number of hops growing at all? I think that could be a potential issue with what I've done.

**Review by JackWilb — APPROVED** [review]
I like these changes, Derya and Jared. The query shouldn't grow over 5 hops, that's already probably too much and it's very intensive to query that far. This design should work into the future!

**Comment by gotdairyya** [comment]
Yes, this looks great, thanks, Jared and Jack. I'll merge master into this branch and then if one of you can approve the PR I will go ahead and merge it

**Review by jtomeck — APPROVED** [review]
💯

**Pull request merged**
